"""Declarative definitions for the validated multi-stroke exercise catalog."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import replace

from ..models import RacketImpactParameters
from ..rally import ExerciseDefinition, ExerciseStroke


LONG_EXERCISE_SERVICE_PARAMS = RacketImpactParameters(
    ball_velocity=(0.0, 0.0, -2500.0),
    ball_omega=(0.0, 0.0, 0.0),
    rubber_friction=1.2,
    rubber_restitution=0.8,
    racket_angle=(80.0, -42.83490642483267, 155.7113197603776),
    racket_velocity=(
        9673.746218778018,
        1996.6902839275556,
        1916.3876524567727,
    ),
    ball_position=(-300.0, 244.0, 1020.0),
)

LONG_FOREHAND_EXERCISE_SERVICE_PARAMS = RacketImpactParameters(
    ball_velocity=(0.0, 0.0, -2500.0),
    ball_omega=(0.0, 0.0, 0.0),
    rubber_friction=1.2,
    rubber_restitution=0.8,
    racket_angle=(80.0, -25.22282587499381, 173.0363434225952),
    racket_velocity=(
        7273.834398299097,
        4287.790847340812,
        4453.512300875377,
    ),
    ball_position=(-300.0, 244.0, 1020.0),
)

# Racket Y/Z angles and X/Y/Z velocity for each expanded three-cycle preset.
# These controls are generated by ``table-tennis search exercise`` and are
# deliberately data-only: incoming ball state and contact position are always
# taken from the preceding simulated segment.
CALIBRATED_CONTROLS = {
    "drive_to_drive": (
        (12.0176038758, 9.12797496643, 3517.96747929, 1722.11724384, 4106.02954275),
        (24.8094685747, -163.130982956, -2546.06851273, -1545.99624427, 4959.96924576),
        (22.7055595364, 19.7772541221, 2907.65794439, 1547.57679077, 4789.57489592),
        (21.6679542874, -160.481941968, -2770.12998963, -1426.56070776, 4899.09805766),
        (22.7748946672, 19.1805356529, 2482.93428397, 1414.85733692, 4928.72779609),
        (22.7830693771, -159.41669016, -3655.41609645, -1788.85858145, 4497.74189563),
        (20.3655185019, 19.6772481947, 1912.69023826, 1246.2208311, 5083.07269744),
        (24.1546177792, -159.941489401, -2678.88170228, -1510.94851768, 4789.33668412),
        (23.7723072671, 20.3178299054, 2584.30322144, 1500.47624735, 4792.99343742),
        (23.9190475817, -159.468232394, -2640.44742774, -1507.81487468, 4787.27027533),
    ),
    "backhand_to_backhand": (
        (12.0176040001, -9.12797482527, 3517.96748743, -1722.11726071, 4106.02955529),
        (24.8094661057, 163.130983932, -2546.0682506, 1545.99625393, 4959.96905998),
        (22.7055592287, -19.7772538165, 2907.65802648, -1547.57673912, 4789.57487526),
        (21.6679539191, 160.481942273, -2770.12992653, 1426.56075183, 4899.0980862),
        (22.774894741, -19.1805360806, 2482.93423406, -1414.85736428, 4928.72778065),
        (22.7830656534, 159.416690042, -3655.4157084, 1788.85859821, 4497.74241645),
        (20.3655151253, -19.6772483295, 1912.68997284, -1246.22083692, 5083.07260629),
        (24.154610595, 159.941488885, -2678.88113747, 1510.94824697, 4789.3362591),
        (23.7723059243, -20.3178295467, 2584.30318811, -1500.47630299, 4792.99336663),
        (23.9190413539, 159.468231792, -2640.44693178, 1507.81462314, 4787.26988235),
    ),
    "figure_eight": (
        (12.766382018, 0.0, 3470.39978768, 0.0, 4217.55185391),
        (26.1029084788, 171.350485888, -3122.09691604, 2013.58683793, 4875.13836277),
        (25.2291240321, -10.7641181924, 2867.80496779, 451.868577321, 5007.41235406),
        (24.5728878287, -170.09582165, -3724.10699217, -2304.8581881, 4602.90666734),
        (23.631003308, 12.3920565636, 2268.65615505, -512.373587959, 5129.42116497),
        (26.8531308781, 172.377089412, -2890.33557956, 2019.52769501, 4842.18125734),
        (27.3808143549, -11.1778216917, 2987.7080995, 353.57446382, 4832.73404947),
        (25.381940929, -171.690800938, -3218.3624261, -2068.37624505, 4830.29338127),
        (25.2724342413, 11.1077552575, 2827.84194486, -393.846462083, 5003.72177232),
        (26.7634275593, 172.28911306, -2886.75215692, 2023.2170936, 4870.97940756),
        (27.2146956597, -11.2216491888, 3001.08911837, 338.914744346, 4851.91676612),
        (25.4243725184, -171.82204255, -3212.98936727, -2071.89326831, 4835.64271579),
    ),
    "falkenberg": (
        (12.0176040001, -9.12797482527, 3517.96748743, -1722.11726071, 4106.02955529),
        (18.0587691445, 161.589969331, -1809.25793049, 1229.29736027, 4880.60889583),
        (36.6867210862, -20.1472087573, 3219.71319894, -2084.91821839, 4941.27848972),
        (19.429880928, 165.128577869, -2441.80336914, -650.738960023, 4450.40811138),
        (46.8044564753, -0.124287632267, 4355.40472037, -29.8390446285, 4790.76241256),
        (18.4352933565, 169.283275472, -1902.26280785, 1817.66185169, 4595.09982916),
        (25.2901750714, -22.3796389209, 3363.12660362, -1778.27750976, 4322.124551),
        (13.9900432563, 157.319485109, -1621.55112782, 971.075080928, 4787.2181317),
        (36.7307280736, -20.146026792, 3283.50135395, -2108.14083823, 4923.93482548),
        (19.3625118375, 165.139035264, -2435.94862568, -652.060768133, 4452.7551205),
        (46.774495129, -0.125361500235, 4353.93193765, -29.8834792177, 4792.2328065),
        (18.4327156332, 169.283757456, -1902.3867413, 1817.56754573, 4595.28625657),
        (25.2897121998, -22.3783740631, 3363.03632624, -1778.27423404, 4322.17777666),
        (13.9901391921, 157.319712065, -1621.54025295, 971.070376917, 4787.22742768),
        (36.7308060867, -20.1459837102, 3283.50798579, -2108.14288659, 4923.9326791),
        (19.3625173985, 165.139042231, -2435.94858704, -652.059992421, 4452.75533713),
        (46.7744970671, -0.125363186176, 4353.93202835, -29.8834639918, 4792.23271484),
        (18.4327157893, 169.283757248, -1902.38675055, 1817.5675315, 4595.28625),
    ),
    "hit_and_pass_forehand": (
        (25.1946479453, 8.64730680806, 5634.64063352, 2330.17218393, 5642.32188786),
        (17.9826651536, -162.471273444, -1498.50914779, -1127.6599462, 5388.90579521),
        (28.3325598141, 21.0163998109, 2150.1247771, 1692.39131778, 4602.86944009),
        (18.1789681587, -153.622522836, -2300.36748695, -1288.44538802, 4075.36417241),
        (40.9733192562, 20.2302160628, 4515.99249964, 2488.57321467, 5406.87600407),
        (15.9290156452, -156.392732701, -1758.60552564, -946.634479416, 4895.83702005),
        (27.7940760305, 21.600326308, 2154.62110834, 1703.44168354, 4551.61829568),
        (17.9905952342, -153.474752922, -2302.84692972, -1278.15368167, 4065.18392485),
        (40.9298013506, 20.2106837899, 4515.49410303, 2488.38817231, 5409.24137927),
        (15.9241166426, -156.402011716, -1758.19380883, -946.456529997, 4896.27291383),
        (27.7926740858, 21.5976689552, 2154.70914517, 1703.3739698, 4551.7792928),
        (17.9908654596, -153.476326289, -2302.83332512, -1278.16765245, 4065.24928499),
    ),
    "hit_and_pass_backhand": (
        (25.1946482645, -8.64730719465, 5634.64067638, -2330.17215232, 5642.32190925),
        (17.9826651035, 162.471273342, -1498.50912685, 1127.65996709, 5388.90578575),
        (28.3325599755, -21.0164000959, 2150.12479385, -1692.39131048, 4602.86944624),
        (18.1789687663, 153.622522755, -2300.36754741, 1288.4453908, 4075.36408683),
        (40.9733188747, -20.2302163174, 4515.99248629, -2488.5731798, 5406.87601679),
        (15.9290158964, 156.392732732, -1758.6055386, 946.634501143, 4895.83704336),
        (27.7940761268, -21.6003260853, 2154.62110764, -1703.4417002, 4551.61829903),
        (17.9905993781, 153.474754095, -2302.84730469, 1278.1534774, 4065.18352622),
        (40.9298074165, -20.2106815331, 4515.49477574, -2488.38803973, 5409.24129802),
        (15.9241180126, 156.402013235, -1758.19381877, 946.456652886, 4896.27299274),
        (27.7926744872, -21.597669333, 2154.70916473, -1703.37395661, 4551.7792964),
        (17.9908647731, 153.4763262, -2302.83321847, 1278.16764859, 4065.24936077),
    ),
    "third_ball_hit_and_pass_forehand": (
        (-39.9175477238, 43.9932890708, 11889.3924389, -3254.64072559, -7032.87100593),
        (-72.6990938547, 152.323708144, -4405.11315804, -2475.79286616, -88.5511666219),
        (22.9118870868, 25.2641771729, 5026.42911118, 2923.50609996, 4974.80242793),
        (14.5635003021, -151.777386319, -1017.29953697, -923.197348231, 5365.26458203),
        (26.9822280113, 23.7492022391, 2106.37173598, 1629.18287415, 4519.85064136),
        (17.8742360408, -153.280734846, -2307.32168307, -1270.6918808, 4054.39404418),
        (40.8773889081, 20.2092914806, 4514.78497334, 2489.38835182, 5411.76475879),
        (15.9209548779, -156.402302001, -1757.87467121, -945.858685039, 4896.77599308),
        (27.7916176182, 21.5956926951, 2154.73303067, 1703.34720777, 4551.89705076),
        (17.9910389511, -153.477250097, -2302.82342677, -1278.17235844, 4065.29393693),
        (40.9305425701, 20.2102115459, 4515.52493905, 2488.36154673, 5409.22093031),
        (15.9241664949, -156.402202425, -1758.1934818, -946.472545716, 4896.27151483),
        (27.7926916686, 21.5976854476, 2154.70970931, 1703.37383979, 4551.77859986),
        (17.9908561459, -153.476313973, -2302.83208854, -1278.16886956, 4065.24985742),
    ),
    "third_ball_hit_and_pass_backhand": (
        (-39.9175477238, 43.9932890708, 11889.3924389, -3254.64072559, -7032.87100593),
        (-67.6496156854, 130.803196611, -4423.91232104, -350.821954185, -72.0582141572),
        (37.2915616821, -28.3478351882, 4729.39600261, -1655.83821089, 5080.17830965),
        (15.9543348439, 161.268800653, -1603.9680362, 1369.16923222, 4890.98765659),
        (28.0547055389, -22.0449758916, 2144.93114304, -1675.34661067, 4528.82926835),
        (17.94413612, 153.449658107, -2310.08734824, 1284.52096792, 4057.2956414),
        (40.811358797, -20.2397058924, 4512.70709053, -2490.17481666, 5416.26198985),
        (15.927036967, 156.394642881, -1757.65789728, 945.124144137, 4897.71383579),
        (27.7932190295, -21.5956805575, 2154.60873401, -1703.42490115, 4551.88129692),
        (17.9910988836, 153.476221477, -2302.8247455, 1278.17338643, 4065.26079453),
        (40.9302337927, -20.2104792303, 4515.51081471, -2488.37497934, 5409.22807686),
        (15.9241502346, 156.402095134, -1758.1942815, 946.464852304, 4896.27168869),
        (27.7926848383, -21.5976804536, 2154.70940772, -1703.37394445, 4551.77874184),
        (17.9908654819, 153.476322978, -2302.83339713, 1278.167647, 4065.24914153),
    ),
    "third_ball_change_of_pace": (
        (-25.222825875, 173.036343423, 7273.8343983, 4287.79084734, 4453.51230088),
        (-36.6217587669, -169.094040398, -3291.60836502, -2003.23520028, -1097.996919),
        (28.8216785992, 16.3172967874, 4855.21878191, 2297.26120882, 5540.01147282),
        (15.7925619368, -157.392661535, -1371.76001611, -990.804206755, 5234.15963489),
        (-53.8546142832, 42.4590978864, 4718.55371597, 1222.56718886, -1465.11149792),
        (27.9770122674, -149.008487073, -3730.97558056, -1870.5745196, 5035.86316552),
        (14.6718361746, 25.6198979076, 1690.31233617, 1240.82851801, 4734.68529518),
        (-53.2024809603, -135.963500443, -4670.80281569, -1228.2235578, -1452.76928934),
        (28.0251442255, 31.2553047345, 3706.60148016, 1892.28923152, 5014.1142759),
        (14.6282946141, -154.021442869, -1687.60375407, -1230.05954469, 4719.59296783),
        (-53.2791904748, 44.1938542012, 4674.01776986, 1231.81811337, -1446.52983499),
        (50.6539424178, 68.4287842463, -6193.71722978, -1763.11357016, 98.3682612269),
        (16.3395002641, 22.4961119597, 1769.76847748, 631.09374641, 5014.19804464),
    ),
    "third_ball_change_of_pace_backhand": (
        (-42.8349064248, 155.71131976, 9673.74621878, 1996.69028393, 1916.38765246),
        (-37.5345952013, 158.778541396, -4474.41649337, 1193.22579847, -1236.0146666),
        (19.9761667284, -24.3508105051, 5205.73871108, -2339.79013724, 5325.59028596),
        (14.8476044318, 157.679044025, -1008.58376068, 1129.44032445, 5657.59507586),
        (-52.8577647959, -43.198545229, 4660.66888905, -1186.90183334, -1496.96631815),
        (50.8286457505, -68.3459543024, -6220.1412639, 1758.74171056, 98.0507506442),
        (16.3917889862, -22.3667574553, 1770.56912177, -629.407519355, 5022.65171873),
        (-55.0772957479, 139.195293323, -4776.13440039, 1244.20975836, -1454.98259976),
        (28.3028157173, -30.7355397178, 3768.87216065, -1864.47627368, 5047.39357397),
        (14.749094049, 154.655601157, -1687.72521177, 1250.63226732, 4742.67469598),
        (-53.1871844005, -43.9825935038, 4669.83670733, -1227.53934208, -1454.6271263),
        (50.6953366956, -68.428963267, -6198.45601479, 1764.36540687, 98.3239769661),
        (16.3497052602, -22.4854707, 1769.96360297, -630.593179002, 5015.48896573),
    ),
}


def _stroke(
    hitter: str,
    wing: str,
    kind: str,
    target_wing: str,
    *,
    pace: str = "regular",
    moment: int = 2,
    fraction: float = 0.45,
    cycle: int = 0,
    label: str = "",
    contact_wing: str | None = None,
    service_preset: str | None = None,
    bounce_tolerance_mm: float = 150.0,
) -> ExerciseStroke:
    return ExerciseStroke(
        hitter=hitter,  # type: ignore[arg-type]
        wing=wing,  # type: ignore[arg-type]
        kind=kind,  # type: ignore[arg-type]
        target_wing=target_wing,  # type: ignore[arg-type]
        contact_wing=contact_wing,  # type: ignore[arg-type]
        pace=pace,  # type: ignore[arg-type]
        contact_moment=moment,  # type: ignore[arg-type]
        contact_fraction=fraction,
        cycle=cycle,
        label=label,
        service_preset=service_preset,
        bounce_tolerance_mm=bounce_tolerance_mm,
    )


def _drive_to_drive(cycles: int) -> tuple[ExerciseStroke, ...]:
    strokes = []
    for index in range(max(5, cycles)):
        cycle = index + 1
        strokes.extend(
            (
                _stroke(
                    "near",
                    "forehand",
                    "drive",
                    "forehand",
                    cycle=cycle,
                    label="Drive cruzado A",
                ),
                _stroke(
                    "far",
                    "forehand",
                    "drive",
                    "forehand",
                    cycle=cycle,
                    label="Drive cruzado B",
                ),
            )
        )
    return tuple(strokes)


def _backhand_to_backhand(cycles: int) -> tuple[ExerciseStroke, ...]:
    strokes = []
    for index in range(max(5, cycles)):
        cycle = index + 1
        strokes.extend(
            (
                _stroke(
                    "near",
                    "backhand",
                    "drive",
                    "backhand",
                    cycle=cycle,
                    label="Revés cruzado A",
                ),
                _stroke(
                    "far",
                    "backhand",
                    "drive",
                    "backhand",
                    cycle=cycle,
                    label="Revés cruzado B",
                ),
            )
        )
    return tuple(strokes)


def _figure_eight(cycles: int) -> tuple[ExerciseStroke, ...]:
    strokes = []
    for cycle in range(1, cycles + 1):
        strokes.extend(
            (
                _stroke(
                    "near",
                    "forehand",
                    "drive",
                    "backhand",
                    cycle=cycle,
                    label="A paralela de drive",
                ),
                _stroke(
                    "far",
                    "backhand",
                    "drive",
                    "backhand",
                    cycle=cycle,
                    label="B cruzada de revés",
                ),
                _stroke(
                    "near",
                    "backhand",
                    "drive",
                    "forehand",
                    cycle=cycle,
                    label="A paralela de revés",
                ),
                _stroke(
                    "far",
                    "forehand",
                    "drive",
                    "forehand",
                    cycle=cycle,
                    label="B cruzada de drive",
                ),
            )
        )
    return tuple(strokes)


def _falkenberg(cycles: int) -> tuple[ExerciseStroke, ...]:
    strokes = []
    for cycle in range(1, cycles + 1):
        strokes.extend(
            (
                _stroke(
                    "near",
                    "backhand",
                    "drive",
                    "backhand",
                    cycle=cycle,
                    label="Revés",
                ),
                _stroke(
                    "far",
                    "backhand",
                    "block",
                    "backhand",
                    cycle=cycle,
                    label="Bloqueo al revés",
                ),
                _stroke(
                    "near",
                    "forehand",
                    "topspin",
                    "backhand",
                    contact_wing="backhand",
                    cycle=cycle,
                    label="Pivote de derecha",
                ),
                _stroke(
                    "far",
                    "backhand",
                    "block",
                    "forehand",
                    cycle=cycle,
                    label="Bloqueo al drive",
                ),
                _stroke(
                    "near",
                    "forehand",
                    "topspin",
                    "backhand",
                    cycle=cycle,
                    label="Derecha",
                ),
                _stroke(
                    "far",
                    "backhand",
                    "block",
                    "backhand",
                    cycle=cycle,
                    label="Bloqueo de reinicio",
                ),
            )
        )
    return tuple(strokes)


def _hit_and_pass(cycles: int, wing: str) -> tuple[ExerciseStroke, ...]:
    strokes = []
    for cycle in range(1, cycles + 1):
        strokes.extend(
            (
                _stroke(
                    "near",
                    wing,
                    "topspin",
                    wing,
                    pace="strong",
                    cycle=cycle,
                    label="Topspin fuerte",
                ),
                _stroke(
                    "far",
                    wing,
                    "block",
                    wing,
                    cycle=cycle,
                    label="Bloqueo",
                ),
                _stroke(
                    "near",
                    wing,
                    "topspin",
                    wing,
                    pace="controlled",
                    cycle=cycle,
                    label="Topspin controlado",
                ),
                _stroke(
                    "far",
                    wing,
                    "block",
                    wing,
                    cycle=cycle,
                    label="Bloqueo",
                ),
            )
        )
    return tuple(strokes)


def _third_ball_hit_and_pass(
    cycles: int,
    wing: str,
) -> tuple[ExerciseStroke, ...]:
    pattern = list(_hit_and_pass(cycles, wing))
    pattern[0] = replace(
        pattern[0],
        contact_moment=2,
        contact_fraction=0.85 if wing == "forehand" else 0.45,
        label="Topspin de tercera bola",
    )
    return (
        _stroke(
            "near",
            "backhand",
            "serve",
            "elbow",
            moment=4,
            fraction=0.55,
            label="Servicio cortado corto",
            service_preset="short",
        ),
        _stroke(
            "far",
            "backhand",
            "push",
            wing,
            moment=4,
            fraction=0.55,
            label=f"Recepción cortada larga al {wing}",
        ),
        *pattern,
    )


def _third_ball_change_of_pace(
    cycles: int,
    wing: str,
) -> tuple[ExerciseStroke, ...]:
    wing_label = "drive" if wing == "forehand" else "revés"
    strokes = [
        _stroke(
            "near",
            "backhand",
            "serve",
            wing,
            moment=2,
            fraction=0.35,
            label=f"Servicio cortado largo al {wing_label}",
            service_preset=f"long_{wing}",
        ),
        _stroke(
            "far",
            wing,
            "push",
            wing,
            moment=2,
            fraction=0.45,
            label=f"Recepción cortada larga al {wing_label}",
        ),
        _stroke(
            "near",
            wing,
            "topspin",
            wing,
            pace="strong",
            moment=2,
            fraction=0.85,
            bounce_tolerance_mm=(
                250.0 if wing == "backhand" else 150.0
            ),
            label=f"Topspin de tercera bola de {wing_label}",
        ),
        _stroke(
            "far",
            wing,
            "block",
            wing,
            label="Bloqueo",
        ),
    ]
    chopper = "near"
    for cycle in range(1, cycles + 1):
        attacker = "far" if chopper == "near" else "near"
        strokes.extend(
            (
                _stroke(
                    chopper,
                    wing,
                    "chop",
                    wing,
                    moment=4,
                    fraction=0.55,
                    cycle=cycle,
                    label=f"Corte defensivo de {wing_label}",
                ),
                _stroke(
                    attacker,
                    wing,
                    "topspin",
                    wing,
                    pace="strong",
                    moment=2,
                    fraction=0.45,
                    cycle=cycle,
                    label=f"Topspin de {wing_label}",
                ),
                _stroke(
                    chopper,
                    wing,
                    "block",
                    wing,
                    cycle=cycle,
                    label="Bloqueo y cambio de roles",
                ),
            )
        )
        chopper = attacker
    return tuple(strokes)


_BUILDERS: dict[str, tuple[str, Callable[[int], tuple[ExerciseStroke, ...]]]] = {
    "drive_to_drive": ("Drive a drive", _drive_to_drive),
    "backhand_to_backhand": ("Revés a revés", _backhand_to_backhand),
    "figure_eight": ("Ochos: paralela contra cruzada", _figure_eight),
    "falkenberg": ("Falkenberg", _falkenberg),
    "hit_and_pass_forehand": (
        "Pega pasa de drive",
        lambda cycles: _hit_and_pass(cycles, "forehand"),
    ),
    "hit_and_pass_backhand": (
        "Pega pasa de revés",
        lambda cycles: _hit_and_pass(cycles, "backhand"),
    ),
    "third_ball_hit_and_pass_forehand": (
        "Tercera bola y pega pasa de drive",
        lambda cycles: _third_ball_hit_and_pass(cycles, "forehand"),
    ),
    "third_ball_hit_and_pass_backhand": (
        "Tercera bola y pega pasa de revés",
        lambda cycles: _third_ball_hit_and_pass(cycles, "backhand"),
    ),
    "third_ball_change_of_pace": (
        "Tercera bola y cambio de ritmo con corte · drive",
        lambda cycles: _third_ball_change_of_pace(cycles, "forehand"),
    ),
    "third_ball_change_of_pace_backhand": (
        "Tercera bola y cambio de ritmo con corte · revés",
        lambda cycles: _third_ball_change_of_pace(cycles, "backhand"),
    ),
}

EXERCISE_NAMES = tuple(_BUILDERS)


def build_exercise(name: str, cycles: int = 3) -> ExerciseDefinition:
    if cycles < 3:
        raise ValueError("Exercise videos require at least three cycles.")
    try:
        title, builder = _BUILDERS[name]
    except KeyError as exc:
        raise ValueError(f"Unknown exercise: {name}") from exc
    return ExerciseDefinition(
        name=name,
        title=title,
        cycles=cycles,
        strokes=builder(cycles),
    )


def build_exercises(
    names: list[str] | tuple[str, ...] | None = None,
    cycles: int = 3,
) -> tuple[ExerciseDefinition, ...]:
    selected = EXERCISE_NAMES if names is None else tuple(names)
    return tuple(build_exercise(name, cycles=cycles) for name in selected)


__all__ = [
    "CALIBRATED_CONTROLS",
    "EXERCISE_NAMES",
    "LONG_EXERCISE_SERVICE_PARAMS",
    "LONG_FOREHAND_EXERCISE_SERVICE_PARAMS",
    "build_exercise",
    "build_exercises",
]
